{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "tomcat-svc", #Service的名称
    "namespace": "default" #Service的命名空间
  },
  "spec": {
    "ports": [
      {
        "name": "tomcat_web",
        "nodePort": 30696,
        "port": 30081,
        "protocol": "TCP",
        "targetPort": 10080
      }
    ],
    "selector": { #用于确定Pod
      "app": "tomcat"
    },
    "type": "NodePort"
  }
}
{
	"apiVersion": "v1",
	"kind":"Service",
	"metadata":{
		"name": "tomcat-svc",
		"namespace":"default"
	},
	"spec": {
		"selector": {
			"app": "tomcat"
		},
		"ports": {
			"name":"test",
			"protocol":"TCP",
			"port":30081,
			"targetPort":8080, #containerPort
			"nodePort":30696 #集群外访问
		},
		"type": "NodePort"
	}
}